//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserImagePreference
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ImageId { get; set; }
        public Nullable<bool> Preference { get; set; }
    
        public virtual tblImage tblImage { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
